name: Node auto deployment
on:
  push:
    branches: [ develop ] #监听master分支的push事件
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest #指定运行环境为最新的Ubuntu版本
    strategy:
      matrix:
        node-version: [15.9.0] #指定node版本
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} #使用action安装node环境
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: ssh scp ssh pipelines #使用市场找到的action来将项目build的产物传到我的服务器
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.LDD_SERVER_IP }} # 服务器的ip
        user: ${{ secrets.LDD_SERVER_NAME }} # 服务器的账号
        pass: ${{ secrets.LDD_SERVER_PASSWORD }} # 服务器的密码
        connect_timeout: 10s
        scp: | #将build生成的文件从GitHub服务器的相应目录，传到我服务器的相应目录
          ./ => /home/node_pro/node1
        last_ssh: | #这部分是在服务器上，传输文件后执行的命令，新版本重新安装依赖并运行
          cd /home/node_pro/node1
          pm2 restart index.js
